const assert = require('node:assert/strict');
const { TourZoomSession, mapZoomLocation } = require('../out/tourZoomSession.js');
const stage = { sceneIndex: 2, stepIndex: 4, path: 'a.ts', navigation: { scrollTop: 80 } };
const session = new TourZoomSession('explanation');
const origin = session.depart(stage);
session.enter('history', { sceneIndex: 0, stepIndex: 0, path: 'a.ts' });
assert.equal(session.depart({ sceneIndex: 0, stepIndex: 0, path: 'a.ts' }), origin);
session.enter('final', { sceneIndex: 0, stepIndex: 0, path: 'a.ts' });
session.depart({ sceneIndex: 0, stepIndex: 0, path: 'a.ts' });
assert.deepEqual(session.enter('explanation', null), { location: stage, restore: true });
session.depart(stage);
session.enter('final', null);
session.navigate();
session.depart({ sceneIndex: 1, stepIndex: 0, path: 'b.ts' });
const mapped = { sceneIndex: 3, stepIndex: 0, path: 'b.ts' };
assert.deepEqual(session.enter('explanation', mapped), { location: mapped, restore: false });
session.depart(mapped); // A mapped landing must not overwrite the old explanation cursor.
session.enter('history', null);
session.navigate();
session.depart({ sceneIndex: 0, stepIndex: 0, path: 'unmapped.ts' });
assert.deepEqual(session.enter('explanation', null), { location: stage, restore: true });
assert.equal(mapZoomLocation({ ...stage, path: 'old.ts', line: 20 }, [{ steps: [{ file: 'new.ts', startLine: 1 }, { file: 'new.ts', startLine: 19 }] }], [{ path: 'new.ts', previousPath: 'old.ts' }]).stepIndex, 1);
assert.equal(mapZoomLocation(stage, [], []), null);
console.log('Tour zoom session tests passed.');
